### ISSUE TITLE
NeuralMinimizer method throws allocation error

### ISSUE THREAD

**Issue by GregoryMorse** [itsoulos/OPTIMUS#2]
Basically every method is working but from NeuralMinimizer I get:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Is this related to not having CLAPACK, or has NeuralMinimizer not been tested perhaps with large functions of e.g. 100-200 variables?

**Comment by GregoryMorse** [comment]
Update: this happens only with the default '--neural_model=neural' model not 'rbf' or 'nnc', etc.  It occurs because `NeuralSampler::trainModel()` calls `Tolmin::Tolmin(Problem*)` with a problem with too many parameters and Tolmin uses n^3 allocation.  Will LBFGS instead of BFGS should resolve this?

**Comment by itsoulos** [comment]
The option --neural_trainmethod has been added in NeuralMinimizer method. For now the available values  are: bfgs (the default value), lbfgs. You can use lbfgs for heavy problems

**Comment by GregoryMorse** [comment]
Thank you, it is indeed working.
